version: '3.9'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - redis

  redis:
    image: redis:6.2
    restart: always
    ports:
      - "6379:6379"

  celery:
    build: .
    command: celery -A src worker -l info
    volumes:
      - .:/app
    depends_on:
      - redis
      - web

  celery-beat:
    build: .
    command: celery -A src beat -l info
    volumes:
      - .:/app
    depends_on:
      - redis
      - web
