# Generated by Django 5.2.5 on 2025-08-21 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_error_transfer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='card_number',
            field=models.CharField(max_length=16, verbose_name='Card number'),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='state',
            field=models.CharField(choices=[('created', 'Created'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled')], default='created', max_length=20),
        ),
    ]
